- PhpAmqpLib/Helper/MiscHelper.php
- tests/Unit/Helper/MiscHelperTest.php
The format argument of sprintf should be bracketed in double quote if interpolation is  needed.
The $x is supposed to expand to either x or X. The single quotes prevent this interpolation and instead are seen as a positional argument spec n$, which is incorrect here.
As it stands, the code generates a "sprintf(): Too few arguments : warning.
> Incorrect quoting of some sprintf formats.

- PhpAmqpLib/Connection/AbstractConnection.php
On a very specific use case the memory_limit of the php script was reached. It occurs when the protocl is abused and very large packets are passed through it.
> abstractconnection prepare_content memory optimization

- PhpAmqpLib/Channel/AbstractChannel.php
Before commit 64eb289c9f5721daa2bd3ad0f333c5b738580843 the property method_queue was public. For one of our project we use celery-php which uses php-amqplib as a dependency. 
To receive status messages from the result queue it is necessary to read the property method_queue. Since it is now protected this is not longer possible.
> add getter for method_queue

- PhpAmqpLib/Connection/AbstractConnection.php
Reconnecting wasn't possible at a brokenpipe runtime exception because isConnected was still true.
> isConnected was still true when broken pipe or close connection

- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Message/AMQPMessage.php
- README.md
If a very large message is received by a consumer, PHP's memory limit may be reached
before the basic_consume callback is even called. To avoid this, the Channel needs to avoid constructing the Message.
Proposed solution is a new public function setMaxBodySize(int $bytes) on Channel; body sizes exceeding this will be truncated, and $msg->is_truncated flag set. A new public property $msg->body_size reflects the true body size (i.e. it higher than strlen($msg->body)).
This allows the callback to check the flat and decide whether to use the truncated data, or nack the message, etc.
The default remains unlimited to avoid compatibility issues, although a default value based on `ini_set('memory_limit')` might be possible.
> Allow a max body size to be set per Channel

- .travis.yml
Since HHVM tests already pass, it would be good to start testing the upcoming versions of PHP & HHVM. Of course we're allowing failures for those cases.
> Include PHP 7 and HHVM Nightly builds in testing suite

- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Functional/AbstractPublishConsumeTest.php
Prevent "UNEXPECTED_FRAME - expected method frame, got non method frame instead" exception when message body length is equal multiplication of 131064 bytes
> Prevent UNEXPECTED_FRAME exception

- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
Wrong typehinting introduced some unclarity, beacase password was typehinted as bool. Now it is changed to string.
> Fix of wrong typehinting of password parameter

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- demo/amqp_consumer_signals.php
Streams that are blocking are unable to interpret signals until a timeout occurs. When working on a connection with a higher timeout or using heartbeats to keep the connection alive, signals will not work. 
Workarounds have been mentioned which set a timeout and loop every x seconds to do a check but this is inefficient for the cpu. Using stream_select with a value of null is the easiest on resources while waiting for input. The only way that input will be caught is if the stream is not blocking.
Fixes #165
Fixes #192 
With a stressed connection and also when writing larger values to the stream the os can queue writes and result in hidden issues with the stream. I have removed the @ and have added a few allowed errors that can occur. Everything else will be raised as an exception so it …
> Fixed signals to respond immediately instead of waiting for timeout.

- PhpAmqpLib/Connection/AbstractConnection.php
We are calling ``wait()`` on channel specifying a timeout that we determined as the time to live of our consumer. The time to live is respected if there are messages being processed but also if we are waiting on the channel for new messages until the time to live defined (10 minutes). 
This worked ok until we enabled heartbeat every 30 seconds to keep connection open behind Amazon ELB. What happens is that we have a timeout of 600 seconds and then (if there are no messages in the queue):
```
wait_frame() is called with 600 seconds timeout
-- after 30 seconds
heartbeat frame is received 
wait_frame() is called with 600 seconds timeout
-- more 30 seconds
heartbeat frame is received 
wait_frame() is called with 600 seconds timeout
(...)
```
This means our consumer will never timeout and do …
> Heartbeat frames decrease timeout on wait_channel (AbstractConnection)

- PhpAmqpLib/Connection/AbstractConnection.php
Changed demo/amqp_consumer.php
```php
while (true)
{
try
{
if (count($ch->callbacks))
{
$ch->wait(null, false, 1);
}
}
catch (AMQPTimeoutException $e)
{
}
catch (AMQPProtocolConnectionException $e)
{
}
}
```
If RabbitMQ restarts while this code is running it leads to PHP fatal error "Call to a member function getTimeout()"
> Fixed fatal error in some cases on Channel.wait with timeout

- .gitattributes
When composer is used as a dependency manager for large web apps,
transferring lots of extra files (such as tests and documentation) can
be very time and bandwidth consuming. By using gitattributes we can
tell composer what files to ignore when distributing through composer.
> Add .gitattributes to slim down composer packages.

- demo/amqp_consumer.php
- demo/amqp_consumer_exclusive.php
- demo/amqp_consumer_fanout_1.php
- demo/amqp_consumer_fanout_2.php
- demo/amqp_consumer_non_blocking.php
- demo/amqp_ha_consumer.php
- demo/amqp_message_headers_recv.php
- demo/amqp_message_headers_snd.php
- demo/amqp_publisher.php
- demo/amqp_publisher_exclusive.php
- demo/amqp_publisher_fanout.php
- demo/amqp_publisher_with_confirms.php
- demo/amqp_publisher_with_confirms_mandatory.php
- demo/basic_cancel.php
- demo/basic_get.php
- demo/basic_nack.php
- demo/basic_qos.php
- demo/basic_return.php
- demo/batch_publish.php
- demo/delayed_message.php
- demo/e2e_bindings.php
- demo/queue_arguments.php
Updated demo code to use AMQPStreamConnection class instead of the deprecated AMQPConnection class. It has been officially deprecated since Nov. 2014, see: videlalvaro/php-amqplib@64eb289#diff-d22541aa1646efa4a61d570b8a0a0ff0
> AMQPConnection class is deprecated.

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/GenericContent.php
- PhpAmqpLib/Wire/IO/StreamIO.php
According to #193, here's the PR that cleans unused code, remove uneeded args but also enforces some method argument type hinting.
Feedback and contribution is very welcomed.
Thanks,
> CS: remove unused args/vars + enforced arg types + various CS fixes

- .scrutinizer.yml
Travis CI can take 15 minutes to run (PHP 5.3).  So I've increased the timeout to wait for code coverage report to 17 minutes.
Also, it now waits for all 4 reports (5.3, 5.4, 5.5, and 5.6).
> Fix Scrutinizer

- .travis.yml
- tests/config.php
In order to do this, I had to have travis use the default vhost and username/password.  Hoping that's not a problem.
> Use new TravisCI infrastructure

- .scrutinizer.yml
- .travis.yml
It looks like, in it's current state, the library supports and passes PHP 7.  Since it will be released soon, do we want to remove PHP 7 from the allowed "failures section" of TravisCI?
> Support PHP 7.0

- PhpAmqpLib/Wire/IO/StreamIO.php
By overwriting the error handler there would be an infinite loop of exceptions, one should always try to restore the error handler. This is just an example of how it should be done througout the project.
Note: one can also use `finally` if PHP >=5.5.
> Fix not restoring error handler

- demo/amqp_publisher_with_confirms.php
- demo/amqp_publisher_with_confirms_mandatory.php
Fixed typos in the 'publish with confirms' examples.
> Typos in the 'publish with confirms' examples.

- PhpAmqpLib/Wire/IO/StreamIO.php
When a large frame is written to the wire over an SSL connection, PHP's OpenSSL extension behaves erroneously upon write failures in non-blocking mode. The fwrite call will return 0. However, if the variable containing the buffer is modified or reassigned, PHP will pass a different pointer to SSL_write(), causing the "bad write retry" error.
This behavior is also produced when a large frame (>= 49,152 bytes) is written directly to the wire with fwrite().
This patch resolves the issue by changing the following behavior:
- Limits fwrite() to 8,192 bytes at a time
- Does not reassign $data if 0 bytes are written
No API breakage. Unit tests are passing.
Datto is using php-amqplib internally and so far we have seen reliability greatly improved with this patch.
> StreamIO: fix "bad write retry" in SSL mode with nonblocking I/O

- PhpAmqpLib/Wire/AMQPAbstractCollection.php
the old decodeCollection function returned an array with uninitialized values. Changing the foreach loop to not use references solved this on PHP7.
> FIXED AbstractCollection value de/encoding on PHP7

- .scrutinizer.yml
- .travis.yml
PHP 7 does not publish code-coverage.  I think that's what is breaking the scrutinizer builds.
Also, hhvm-nightly is no longer supported on Travis.
> Remove hhvm-nightly and fix PHP 7 causing scrutinizer errors

- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/IO/StreamIO.php
Problem:
When closing connection checking for heartbeat it could enter a loop and sometimes it tries to allocate a lot of memory when reading from socket.
Disabling heartbeat on `StreamIO` when closing connection prevents that from happening.
I was unable to reproduce the error with a test and that is why I didn't write one.
PS: The heartbeat value used when error occurs was `10`
> Disable heartbeat when closing connection

- PhpAmqpLib/Helper/Protocol/MethodMap080.php
- PhpAmqpLib/Helper/Protocol/MethodMap091.php
- PhpAmqpLib/Helper/Protocol/Protocol080.php
- PhpAmqpLib/Helper/Protocol/Protocol091.php
- PhpAmqpLib/Helper/Protocol/Wait080.php
- PhpAmqpLib/Helper/Protocol/Wait091.php
- PhpAmqpLib/Wire/Constants080.php
- PhpAmqpLib/Wire/Constants091.php
- spec/parser.php
I also updated some variables from `$args` to the appropriate `$reader` and `$writer` for clarity.
The only thing that _might_ break backwards compatibility is adding the `AMQPReader` and `AMQPWriter` type-hint to some of the method definitions.  That would only come into effect though, if users are extending and overwriting those methods (which I doubt people would do right?)
> Add PHPDocs to Auto-generated Protocol Classes

- PhpAmqpLib/Exception/AMQPIOWaitException.php
- PhpAmqpLib/Wire/AMQPReader.php
A follow-up on this:
https://github.com/videlalvaro/php-amqplib/pull/264
And this:
https://github.com/videlalvaro/php-amqplib/pull/224
amqplib now processes stream_select warning. But it returns false. And AMQPReader throws AMQPRuntimeException.
My implementation did re-run stream_select with getting whatever it returns.
I need to catch an exception when stream_select fails so I can call upon channel wait again, but AMQPRuntimeException is a very general one and filtering exception by its message text is not a good practice.
I propose to throw different exception so you can catch stream_select failure and do something about it. It extends from AMQPRuntimeException so it doesn't break library behavior.
> AMQPReader::wait() throw IOWaitException on stream_select failure

- PhpAmqpLib/Connection/AbstractConnection.php
A neater and more concise fix for #338.
When a frame_type is read from a message, get the list of valid frame types for the protocol version in use, and validate against them, throwing an AMQPRuntimeException if invalid.
> Get the array of valid frame types from the protocol constants class

- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/StreamIOTest.php
Should fix: https://github.com/php-amqplib/php-amqplib/issues/378
> Fix for when the default error handler is not restored

- PhpAmqpLib/Wire/IO/StreamIO.php
This is a follow-up of #378 and #379. The commit messages should be enough to explain the bugfix.
The only problem is that I don't really know how to test the other three places where the error handler is used: I have no idea how to mock php core functions, and I can't think of a way to reproduce the potential errors. Any suggestion is welcome.
> Error handler issue

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPException.php
- PhpAmqpLib/Exception/AMQPProtocolException.php
- PhpAmqpLib/Helper/DebugHelper.php
- PhpAmqpLib/Helper/MiscHelper.php
- PhpAmqpLib/Helper/Protocol/MethodMap080.php
- PhpAmqpLib/Helper/Protocol/MethodMap091.php
- PhpAmqpLib/Helper/Protocol/Protocol080.php
- PhpAmqpLib/Message/AMQPMessage.php
- PhpAmqpLib/Wire/AMQPAbstractCollection.php
- PhpAmqpLib/Wire/AMQPArray.php
- PhpAmqpLib/Wire/AMQPDecimal.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/AMQPTable.php
- PhpAmqpLib/Wire/AMQPWriter.php
- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
* Added missing doc blocks
* Added missing parameter/return types in doc blocks.
Most integer parameter types were hinted using `int` rather than `integer`, and booleans as `bool` rather than `boolean`. I changed any `boolean` types to `bool` and `integer` types to `int` to stay consistent.
> Add Missing DocBlocks and Types

- PhpAmqpLib/Wire/IO/StreamIO.php
It seems that PHP 7 behaves differently than PHP 5.\* - original mb_substr's output exists side-by-side with the original value of $data variable, which leads to doubling used memory. The bigger the $data is, the worse it is.
> Reduce memory usage in StreamIO::write()

- PhpAmqpLib/Wire/AMQPReader.php
mb_strlen will error if passed null on HHVM, this is a workaround for that.
> Bugfix for HHVM compatability

- PhpAmqpLib/Wire/IO/StreamIO.php
HHVM will error if `sec` or `usec` are null, and they are specifically passed as null here: https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L227
> Ensure integer values are actually integers for HHVM compatibility

- README.md
Processes that terminate in response to a signal must not exit manually, but instead terminate themselves using the received signal number, so that calling programs can reliably determine the cause of the termination. This is important for example in scripted bash loops to correctly terminate on Ctrl+C.
> Fix signal handling exit example

- PhpAmqpLib/Wire/IO/StreamIO.php
When consuming and waiting for a message, if server becomes suddenly unreachable (network split, machine fail) only the StreamIO select is called (possibly with a timeout) in `AMQPReader::wait()` and exists with an exception: AMQPTimeoutException that can be handled successfully and StreamIO read is never called to be able to trigger heartbeat logic.
We use this pattern with calling `AMQPChannel::wait()` with 1 second timeout while consuming in order to do some other checks and want to rely on heartbeat in this case also.
We use it in a worker and need to detect as soon as possible when the connection drops but messages might get into the queue with one hour interval.
Was thinking about adding it to the StreamIO write method also.
From what I can see, the heartbeat logic is fast and I'm …
> half-open connection detection with heartbeat while reapeating 

- PhpAmqpLib/Wire/IO/StreamIO.php
The problem this PR fixes is:
* StreamConnection with heartbeat is created (e.g. heartbeat=10 seconds)
* Start consuming messages from the queue
* If one of the messages take more than 2*heartbeat interval to process (e.g. 30 seconds), the next time it tries to read something from Rabbit it will check_heartbeat()
* As it finds that it passed more than 2*heartbeat, it will reconnect()
* But as it does not reset the values of ``last_read`` and ``last_write``, after reconnect it will do the check_heartbeat() again and as it is based on ``last_read``, it will try to reconnect again
* It keeps trying to reconnect in infinite loop
This PR fixes issues: https://github.com/php-amqplib/php-amqplib/issues/413 and https://github.com/php-amqplib/php-amqplib/issues/309
> Fix infinite loop on reconnect - check_heartbeat

- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/IO/StreamIO.php
I found that if a consumer with client heartbeats enabled loses and re-establishes the connection it will not send client heartbeats, causing the server to eventually force a disconnect (I am using AMQPStreamConnection / StreamIO).
This is because StreamIO::disableHeartbeat is called on close(), setting StreamIO::heartbeat to 0, disabling the sending of client heartbeats.
However the matching value AMQPStreamConnection::heartbeat is not altered, so the connection.tune / connection.tune_ok messages still define a client heartbeat, so the server is expecting one.
This PR adds a StreamIO::reenableHeartbeat method which is called after successful reconnection and sets the StreamIO::heartbeat value back to what it was set to in the constructor.
> Re-enable heartbeats after reconnection

- PhpAmqpLib/Wire/AMQPAbstractCollection.php
- tests/Unit/Wire/AMQPCollectionTest.php
Rather than checking for \DateTime objects directly, check for the
\DateTimeInterface added in PHP 5.5. Since older versions are still
supported, a redundant check for \DateTime is left in place.
Reading a timestamp still always returns a DateTime object.
> Add support for serializing DateTimeImmutable objects

- README.md
Hi,
`declare(ticks=1)` is no longer needed to support unix signal handling after PHP 5.3 and [version 90b8cb77fd0fadd313fe60e72d3451e67b29b6fb](https://github.com/php-amqplib/php-amqplib/commit/90b8cb77fd0fadd313fe60e72d3451e67b29b6fb) of this project when [`pcntl_signal_dispatch`](http://php.net/manual/en/function.pcntl-signal-dispatch.php) was introduced. I've updated the README to reflect this.
Please see the following documentation in the PHP manual and Stackoverflow thread for more details
* http://php.net/manual/en/function.pcntl-signal.php
* http://stackoverflow.com/questions/17906758/whats-the-relation-between-declareticks-and-a-signal-handler-in-php
It's also worth noting that `declare(ticks=1)` comes with some expensive CPU overhead, per this comment in the PHP Manual
> Remember …
> declare(ticks=1) no longer needed after PHP5.3 / amqplib 2.4.1

- PhpAmqpLib/Connection/AbstractConnection.php
\PhpAmqpLib\Connection\AbstractConnection::channel() param $channel_id changed from `string` to `integer`.
Non-integer value is causing error:
```
Error on AMQP connection <0.390.0> (127.0.0.1:51356 -> 127.0.0.1:5672, vhost: '/', user: 'guest', state: running), channel 0:
operation channel.open caused a connection exception channel_error: "unexpected method in connection state running"
```
> Fix invalid annotation for channel_id

- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Wire/IO/SocketIO.php
As an answer for #272 where `AMQPSocketConnection` was an issue.
Actual heartbeat code is taken from `StreamIO` with adaptation to sockets.
Also includes splitting of receive timeout and send timeout as it's done in `StreamIO`, though there it's `$connect_timeout` and `$read_write_timeout` which is hard to be accomplished for sockets
As soon as this PR is merged I need to update bundle as it passes options incorrectly (or better mimic same constructor everywhere? or better have a builder to fade out all discrepancies between different connection types).
> bring heartbeat support to socket connection

- PhpAmqpLib/Helper/DebugHelper.php
Allow redirecting debug output to somewhere else than STDOUT - like STDERR or any other stream/file (like Monolog stream wrapper)
> Redirect debug output to `defined` destination

- PhpAmqpLib/Helper/DebugHelper.php
Some environments may not have these constants defined.
> Ensure STDOUT and others constants

- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
This passes the connection timeout parameter defined in AMQPStreamConnection to the AbstractConnection class where it is used when opening and closing the connection
> pass connection timeout to wait method

- PhpAmqpLib/Channel/AMQPChannel.php
callback is not a type and this will throw off tools like phpstan.
> Use phpdoc type that actually exists

- PhpAmqpLib/Wire/IO/StreamIO.php
Fixes #516 
Fixes #449 
`tcp_nodelay` option for stream was added since PHP-7.1.0, benchmark shows great improvements.
before:
```
Stream produce 100:
php benchmark/stream_tmp_produce.php 100
5.1695640087128
Socket produce 100:
php benchmark/socket_tmp_produce.php 100
0.29251194000244
```
with `tcp_nodelay` option:
```
Stream produce 100:
php benchmark/stream_tmp_produce.php 100
0.28404712677002
Socket produce 100:
php benchmark/socket_tmp_produce.php 100
0.32037281990051
```
root@32e5c526ee1c:/mnt# php -v
PHP 7.1.10 (cli) (built: Oct 10 2017 01:16:36) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
> Use tcp_nodelay for StreamIO, fixed #516 #449

- PhpAmqpLib/Wire/IO/StreamIO.php
Long-running processes should be allowed to manually call the StreamIO check_heartbeat method every so often.
> Change protected method check_heartbeat to public

- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
If an IO detects missed heartbeats, it should not reconnect because
the AMQP connection and channels will not be recovered and server-side
connection and channels will be stopped on TCP connection close or
heartbeat timeout.
The current reconnection logic leads to delayed exception, if the client
waits for messages or tries to publish/ack.
It also will create a TCP connection on the server, which will consume
socket descriptors and memory.
Replace reconnect on missed heartbear with close and exception.
Since handling exceptions is a way to address connection issues in the
client, reconnection logic should be moved to exception handlers and be
higher-level, so channels and consumers can be recovered.
Addresses #309
> Throw exception on missed heartbeat

- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- README.md
- demo/amqp_connect_multiple_hosts.php
- demo/connection_recovery_consume.php
Add a new static method `create_connection` in `AbstractConnection`
to create a connection providing multiple hosts.
The method takes an array of host arrays
with host,port,username,password and vhost keys
and tries to connect to them one-by-one.
The first successful connection is returned.
If unable to connect to any of them - the last esception is thrown.
This method is a simplest way to address issues like #253 or #498
There is no bookkeeping and load balancing, hosts are
selected one-by-one starting from the first one.
Combined with connection recovery techniques it can be used
to improve reliability when using clusters.
> Introduce a method to create connection from multiple hosts.

- PhpAmqpLib/Wire/IO/StreamIO.php
If the socket is broken and pcntl is not available, the read method were stuck in an endless loop.
This change checks the hearbeat if no data is read from the stream (potential dead stream).
> Fix heartbeat-check if pcntl is unavailable

- PhpAmqpLib/Wire/AMQPAbstractCollection.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/AMQPWriter.php
- tests/Unit/Wire/AMQPReaderTest.php
- tests/Unit/Wire/AMQPWriterTest.php
```                                                                                                                                                                                                PHP Fatal error: Uncaught exception "PhpAmqpLib\Exception\AMQPOutOfRangeException" with message "0 - AMQP-rabbit doesn't define data of type [x]" in app/start.php                                  
Stack trace:                                                                                                                                                                                       
#0 /app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(389): getDataTypeForSymbol(string);                                                                                          
#1 …
```
> Add extended datatype for bytes

- PhpAmqpLib/Wire/IO/StreamIO.php
Throwing an exception in an error handler halts execution of the program.  This patch throws an exception instead of halting execution.
> don't throw an exception in an error handler

- PhpAmqpLib/Channel/AbstractChannel.php
Thrown at \PhpAmqpLib\Wire\IO\StreamIO::error_handler
This probably is solved at #564, but at least knowing the annotation would be very useful
> Annotate at @throws \ErrorException at AbstractChannel::wait

- PhpAmqpLib/Wire/IO/StreamIO.php
When the underlying tcp connection disconnected for any reason, the next call to basic_publish will freeze the application indefinitely. 
Translating ErrorException to AMQPRuntimeException inside the write function will fix the issue, in this case the exception will be caught by AbstractConnection class `write` method and marked the connection as closed, which then the application be able to detect the connection close and try to reconnect.
> Fwrite \ErrorException not being thrown to the top function call when doing basic_publish

- PhpAmqpLib/Wire/IO/StreamIO.php
System errors strings might be localised. In case of non-english error messages (that's our case, `LANG` is set by application to another value than default), `EAGAIN` and `EINTR` were not correctly detected and caused client to fail with an exception, as the error was not ignored.
> Use errno instead of error strings

- demo/delayed_message.php
This demo will throw fatal error, because it using `basic_nack` with the setting `no_ack = true`.
Fatal message like that:
```
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPProtocolChannelException: PRECONDITION_FAILED - unknown delivery tag 1
``
> fix the logical error

- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPChannelClosedException.php
- PhpAmqpLib/Exception/AMQPConnectionClosedException.php
- PhpAmqpLib/Exception/AMQPDataReadException.php
- PhpAmqpLib/Exception/AMQPHeartbeatMissedException.php
- PhpAmqpLib/Exception/AMQPInvalidFrameException.php
- PhpAmqpLib/Exception/AMQPNotImplementedException.php
- PhpAmqpLib/Exception/AMQPSocketException.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/Channel/DirectExchangeTest.php
- tests/Functional/Channel/TopicExchangeTest.php
- tests/Unit/Wire/IO/SocketIOTest.php
So far, handling runtime exceptions might be clumsy. For example, writing code which reacts to the connection being closed currently relies on the exception message `'Broken pipe or closed connection'`. Rather than throwing the general `AMQPRuntimeException`, specific exceptions shall be used in reasonable situations.
The patch is backwards-compatible as all new exception classes extend `AMQPRuntimeException`.
> Use specific exceptions instead of general AMQPRuntimeException

- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Unit/Connection/LibraryPropertiesTest.php
Added a new method getLibraryProperties to allow custom connections to override the client-properties sent to RabbitMQ
> Add getLibraryProperties abstract connection method and test

- CHANGELOG.md
- composer.json
Fixes #608
Please see this comment as to why this is not going to be considered a breaking change:
https://github.com/php-amqplib/php-amqplib/issues/608#issuecomment-432694398
> Move ext-sockets from "suggest" to "require"

- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/StreamIOTest.php
After 2.8.0 version got released there is a problem with restoring previous error handler in StreamIO class. 
In several places the `restore_error_handler()` was called twice in one function (once by calling `$this->cleanup_error_handler()` and later on by calling  `restore_error_handler()` directly) and because of that the previous error handler was not set correctly since each call popped the previous handler from the stack. 
This PR removes unnecessary calls to  `restore_error_handler()`.
> Fixed restoring previous error handler in StreamIO

- PhpAmqpLib/Wire/IO/StreamIO.php
Parse error string to determine error number instead of using $errno, as $errno is the error level (e.g. E_NOTICE) and not the error number.
> Parse error string to determine error number instead of using errno

- PhpAmqpLib/Wire/IO/StreamIO.php
Fixes #617 
This is in-line with the `SocketIO` implementation.
> Restore code that sets last_read

- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/Bug/Bug458Test.php
Fixes bug that was reintroduced after commit ef318f1 that causes stream_select to raise an exception after the process receives a signal (issue #458).
The bug can be easily reproduced by running the **demo/amqp_consumer_signals.php**
The bug didn't have any tests, that's why the build passed.
> Fix and add test for signal handling with PCNTL extension

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Functional/Channel/ChannelTimeoutTest.php
- tests/Unit/Connection/AMQPSocketConnectionTest.php
- tests/Unit/Connection/AMQPStreamConnectionTest.php
Add a new optional parameter allowing to specify a timeout for channel RPC operations (such as declaring an exchange, closing the channel etc.). This should allow clients to fail-fast if the server is unable to provide a response in time, e.g. because of a resource-driven alarm (see https://github.com/php-amqplib/php-amqplib/issues/88).
The default value for this new parameter is 0, i.e. no timeout which is the current behavior.
cc: @lukebakken
> Allow to specify a timeout for channel operations

- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Unit/Wire/IO/StreamIOTest.php
After 2.8.0 stream connections throws \ErrorException on usual SIGTERM signals. Various libraries cannot detect what caused this generic exception and how to behave next. Would be nice to get specific exception in such cases.
> Fix wrong exception type on stream timeouts and signals

- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPNoDataException.php
- PhpAmqpLib/Helper/MiscHelper.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- demo/amqp_consumer_non_blocking.php
- tests/Functional/Channel/ChannelWaitTest.php
- tests/Functional/StreamIOTest.php
- tests/config.php
This one is mostly focused on $channel->wait() function and related issues. Previously this function throwed exception if no data was received in `connection_timeout` time, but most of us expect it to run indefinitely(timeout=0), like people complaining in #547 and #636.
- fix channel read error and endless loop #622
- make non blocking operations trully non blocking - just poll socket state and do not try to read anything if there is no data ready, introduce AMQPNoDataException
- cover stream & socket connections with same tests
- fix potentially unclosed sockets on connect exceptions - hhvm & docker for mac does not like those
- configurable test options via ENV
> Fix channel wait timeouts and endless loops

- .travis.yml
Latest HHVM 4.0 is not compatible with PHP and no longer able to execute composer.
> Drop support for HHVM

- .travis.yml
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- composer.json
This cleanups some strange workaround for HHVM and follows recommended way of how to push code coverage to scrutinizer.
> Remove workarounds for hhvm, use latest version of scrutinizer tool

- CHANGELOG.md
- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- demo/amqp_connect_multiple_hosts.php
- tests/Functional/Channel/ChannelWaitTest.php
- tests/Unit/Wire/IO/SocketIOTest.php
- tests/Unit/Wire/IO/StreamIOTest.php
Heartbeats are set to 60 seconds by default, with socket timeouts set to 130 seconds.
Fixes #563
> Enable heartbeats by default

- docker-compose.yaml
- docker/php/Dockerfile
- tests/config.php
Based on PHP5.4 as it is minimal supported version.
Fo the first time:
`docker-compose up -d`
`docker-compose exec php composer install`
to run tests:
`docker-compose exec php vendor/bin/phpunit`
> Docker dev environment

- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
* fix unhandled warning in SocketIO on failed connect
* add heartbeat support for socket connections
* move common methods and properties to abstract class
* fix docblocks
> IO improvements

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPConnectionClosedException.php
- PhpAmqpLib/Exception/AMQPTimeoutException.php
- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- README.md
- composer.json
- demo/connection_recovery_consume.php
- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Bug/Bug256Test.php
- tests/Functional/Connection/ConnectionClosedTest.php
- tests/Functional/Connection/ConnectionUnresponsiveTest.php
- tests/Functional/ToxiProxy.php
This adresses mostly broken connection handling and proper flag/variable cleanup.
* Handle various connection problems and throw AMQPConnectionClosedException
* Fix endless loop when writing to blocked stream, i.e. unresponsive vpn connection #624 
* Reset connection/channel state, clear callbacks so consumers knows when to stop waiting, allow reconnect, issue #389 
* Write data to socket/stream split in 8k chunks - improves stability and predictability for non-blocking connections
* replace socket_read with socket_recv because latter do not mix read data with syscall output therefore error handling becomes easier
* introduce https://github.com/Shopify/toxiproxy, add tests for blocked/closed connections, those skipped on travis cause need to figure out how to run proxy there
* minor …
> Handle broken pipe or closed connection exceptions

- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/StreamIOTest.php
PHP cannot enable tcp keepalive feature on ssl connections due to bug https://bugs.php.net/bug.php?id=70939
No workaround exists so we should raise proper exception about incompatible options.
Always set verify_peer to true, to make sure behaviour is same for older PHP versions.
Fix wrong default read_write_timeout after #648
> Throw exception if keepalive cannot be enabled on ssl connections

- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Wire/IO/StreamIO.php
Fixes #641
Allows using tls, tlsv1.0, etc as an argument to AMQPSSLConnection ctor
@Cyrille37 please test this branch in your environment.
> Allow choosing a different protocol for SSL/TLS

- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPHeartbeatMissedException.php
Fixes #627
@programmer512 please review and test if you have time, thanks.
@ramunasd - if you have a second to read #627 and review, I would appreciate it.
> Catch a couple exceptions in select

- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/Bug/Bug256Test.php
- tests/Functional/Bug/Bug40Test.php
- tests/Functional/Bug/Bug458Test.php
- tests/Functional/Bug/Bug49Test.php
- tests/Functional/Channel/ChannelTestCase.php
- tests/Functional/Channel/ChannelTimeoutTest.php
- tests/Functional/Connection/ConnectionClosedTest.php
- tests/Functional/FileTransferTest.php
- tests/Functional/ReconnectConnectionTest.php
* error number from stream connection warnings means error level, not actual error, so we must "extract" it from error message, fix regression after #653 on line:
https://github.com/php-amqplib/php-amqplib/pull/653/files#diff-593ddf6cbc93f7e4518ba0d20c13a8d7R250
* handle same kind of connection issues in both stream and socket connections
* fix unclean functional test tear down
> Fix wrong error code on stream connection exception

- PhpAmqpLib/Connection/AbstractConnection.php
To ensure the client status can be closed when network had been rst.
> Ensure amqp client status is closed that network had been rst

- PhpAmqpLib/Connection/AbstractConnection.php
PR #675 introduced issue with connection close because AbstractConnection->close() sets flag too early, right before check:
```
if (empty($this->protocolWriter) || !$this->isConnected()) {
return $result;
}
```
So everything else after this check became dead code. Besides fix for this issue I added "hard" close on any exception during closing process.
> fix regression after #675 due to too early changed flag

- PhpAmqpLib/Connection/AMQPSSLConnection.php
Introduced in #658, stream context is always SSL activated and causing some compatibility issues. This PR reverts that and allows AMQPSSLConnection to be insecure even if ssl protocol is `ssl` or `tls`. At least one option must be provided to activate secure context/connection.
> Revert default SSL options

- PhpAmqpLib/Channel/AMQPChannel.php
`AMQPChannel::getTicket()` as well as most of the public methods in `AMQPChannel` accept a `$ticket` parameter, which is a nullable integer (either an integer or `null`). This was not always correctly documented in PHPDoc.
> Adjust PHPDoc for AMQPChannel's "$ticket" parameters

- PhpAmqpLib/Exception/AMQPEmptyDeliveryTagException.php
- PhpAmqpLib/Message/AMQPMessage.php
- tests/Unit/Message/AMQPMessageTest.php
Pretty obvious PR. Added helper method for [RabbitMQ delivery tags](https://www.rabbitmq.com/confirms.html#consumer-acks-delivery-tags) + test. Casting it to int, because official docs says it's `monotonically growing positive integers`.
> getDeliveryTag method for AMQPMessage

- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Functional/Connection/ConnectionCreationTest.php
I tried to run unittests but it's impossible on php 7.3
> allow assoc array and generator for connection creation

- PhpAmqpLib/Connection/AbstractConnection.php
In response to #696, add method to trigger heartbeat check manually without access to IO adapter.
> Add connection heartbeat check method

- PhpAmqpLib/Channel/AMQPChannel.php
- tests/Functional/Connection/ConnectionClosedTest.php
Fix for #698 
throws AMQPChannelClosedException like in other methods with same exception message.
> fix call to a member function o null when connection was closed

- .travis.yml
- README.md
- composer.json
- docker/php/Dockerfile
Old supported versions like 5.4 and 5.5 became unpopular and rarely used. According to packagist statistics[1] only 1.5% of all installs use PHP 5.5, 5.4 less than 1%. Meanwhile 5.5 and 5.6 has some very nice improvements and features like generators, finally keyword, support for constant array/string dereferencing and scalar class names via constant ::class.
[1] https://blog.packagist.com/php-versions-stats-2019-1-edition/
[2] https://www.php.net/releases/5_5_0.php
[3] https://www.php.net/releases/5_6_0.php
> Set minimum PHP version to 5.6

- .travis.yml
According to travis-ci docs:
> RabbitMQ can be launched on Ubuntu Xenial using the APT addon in .travis.yml
and by default it is not enabled anymore. This is reason why recent build fails.
> Install RabbitMQ package before travis tests

- tests/phpinfo.php
Just a simple script to output all related PHP information for debug purposes. Should help in cases when somebody reports issue _this constant is not defined for me_.
> PHP information script

- PhpAmqpLib/Helper/SocketConstants.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
This wrapper for sockets extension constants helps to avoid warnings when some constants are not defined in various operating systems or PHP versions.
Triggers warning when sockets extension is not enabled and user will be informed about it. Prevents from cases like #705.
Also there is no need to manually define constants which can cause weird conflicts with other libraries.
Fix #723
> Wrapper for sockets extension constants

- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Connection/ConnectionUnresponsiveTest.php
Initialize variable AbstractConnection->last_frame and prevent from wrong exception type when client can't get response from broker.
Fix for #713
> Fix wrong exception type on failed connect to broker

- tests/Functional/Bug/Bug458Test.php
This test always calls `$this->channel->close()` even if it is skipped due to missing pcntl extension or failed connection to broker. Exception message:
```
PHP Fatal error:  Call to a member function close() on null in .../php-amqplib/php-amqplib/tests/Functional/Bug/Bug458Test.php on line 26
```
Affects mostly windows and macos operating systems.
> Fix fatal error in skipped tests

- .gitignore
- Makefile
- composer.json
Let's remove rarely used phpDocumentator and long list of conflicting dependencies. We can download this tool on demand, just before documentation is being generated.
Improves CI build time.
> Remove phpDocumentator from dev dependencies

- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- docker-compose.yaml
- tests/Functional/Channel/DirectExchangeTest.php
- tests/Functional/Channel/TopicExchangeTest.php
- tests/Functional/Connection/ConnectionAuthTest.php
Current default and single availale authentication method is `AMQPLAIN` which is non standard and retained for BC. This PR adds support for standard simple `PLAIN` and other(non rabbitmq based) brokers.
> Add support for PLAIN authentication method

- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPProtocolConnectionException.php
Just use same exception as in other places for consistency.
Deprecating \PhpAmqpLib\Exception\AMQPProtocolConnectionException which can store some additional meta data, but usually it is just 2 zero digits.
> throw AMQPConnectionClosedException when broker wants to close connection

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Wire/AMQPDecimal.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/AMQPWriter.php
- PhpAmqpLib/Wire/AbstractClient.php
- README.md
- composer.json
- docker/php/Dockerfile
- tests/Unit/Wire/AMQPReaderTest.php
- tests/Unit/WireTest.php
Based on #737 by @terrafrost
* completely remove all bcmath functions
* take advantage of pack/unpack modifiers available since PHP 5.6.3 on 64-bit systems
* try to parse values between PHP_INT_MIN and PHP_INT_MAX if possible
* fallback to BigInteger if cannot encode/decode to native integer, phpseclib added as dependency
* cache in memory repetitive BigInteger values to minimize heavy constructor impact
* tested on native 32 bit platform RaspberryPi
* tested on Windows(appveyor), both 32 and 64 bits https://ci.appveyor.com/project/ramunasd/php-amqplib/builds/28751717
* increased `basic_publish()` performance `time php benchmark/producer.php 10000` user time 0.26s vs. 0.34s
> Remove bcmath dependency

- .gitattributes
- PhpAmqpLib/Connection/AbstractConnection.php
- README.md
- appveyor.yml
- tests/Functional/Bug/Bug256Test.php
- tests/Functional/Bug/Bug40Test.php
- tests/Functional/Bug/Bug458Test.php
- tests/Functional/Bug/Bug49Test.php
- tests/Functional/Channel/ChannelTestCase.php
- tests/Functional/Channel/ChannelTimeoutTest.php
- tests/Functional/Channel/ChannelWaitTest.php
- tests/Functional/Channel/DirectExchangeTest.php
- tests/Functional/Channel/HeadersExchangeTest.php
- tests/Functional/Channel/TopicExchangeTest.php
- tests/Functional/Connection/ConnectionUnresponsiveTest.php
- tests/Functional/FileTransferTest.php
- tests/Functional/ReconnectConnectionTest.php
- tests/Functional/StreamIOTest.php
- tests/Functional/ToxiProxy.php
- tests/Unit/Wire/IO/SocketIOTest.php
- tests/Unit/Wire/IO/StreamIOTest.php
- tests/phpinfo.php
Run phpunit tests on AppVeyor CI platform.
- against all supported php versions
- use 64 and 32 bit windows platforms
- partly based on pika appveyor scripts
- imaproved phpunit annotations
- output PHP integer size as general info
> Run phpunit on appveyor

- .scrutinizer.yml
- .travis.yml
- PhpAmqpLib/Channel/AMQPChannel.php
- appveyor.yml
- phpunit.xml.dist
- tests/Functional/Bug/Bug40Test.php
- tests/Functional/Bug/Bug49Test.php
- tests/Functional/Channel/ChannelWaitTest.php
- tests/Functional/Connection/ConnectionAuthTest.php
- tests/Unit/Wire/IO/SocketIOTest.php
- tests/Unit/Wire/IO/StreamIOTest.php
- some tests does not have any asserts and gets reported by phpunit
- exclude more incompatible tests for travis and appveyor
- report all errors types during tests, including notices and deprecations
- perform code coverage only once per build
- other minor improvements and style fixes
> Fix phpunit tests reported as risked

- tests/Functional/Bug/Bug256Test.php
- tests/Functional/Bug/Bug40Test.php
- tests/Functional/Bug/Bug458Test.php
- tests/Functional/Bug/Bug49Test.php
- tests/Functional/Channel/ChannelTestCase.php
- tests/Functional/Channel/ChannelTimeoutTest.php
- tests/Functional/Channel/DirectExchangeTest.php
- tests/Functional/Channel/HeadersExchangeTest.php
- tests/Functional/Channel/TopicExchangeTest.php
- tests/Functional/FileTransferTest.php
- tests/Functional/ReconnectConnectionTest.php
- tests/Unit/Helper/Protocol/Protocol091Test.php
- tests/Unit/Wire/AMQPReaderTest.php
- tests/Unit/Wire/AMQPWriterTest.php
Following up on https://github.com/php-amqplib/php-amqplib/pull/657. These changes are not usable as-is as long as PHP 5 is still supported.
> Adapt to PHPUnit 8

- composer.json
To avoid other people hitting the issue with stream error handling reported in #764, this PR adds conflict with PHP >=7.4.0 && <7.4.2.
Upstream bug report: https://bugs.php.net/bug.php?id=79000
Closes #764.
> Restrict PHP 7.4.0 - 7.4.1 due to a PHP bug

- Makefile
Change phpDocumentator template and fix #769
> change phpDocumentator template, fix incorrect constructor documentation

- PhpAmqpLib/Connection/AbstractConnection.php
I ran into a scenario where I was accidentally passing an empty array of hosts to `AbstractConnection::create_connection`. 
In this case, the error presented to me was `Error: Can only throw objects`, because `$latest_exception` was `null`.
> fix: ensure hosts is an array, otherwise latest_exception can be null

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Exception/AMQPConnectionBlockedException.php
- PhpAmqpLib/Helper/Assert.php
- demo/batch_publish.php
- tests/Unit/Channel/AMQPChannelTest.php
- tests/Unit/Test/BufferIO.php
- tests/Unit/Test/TestChannel.php
- tests/Unit/Test/TestConnection.php
This library has support for blocked connection. Hovewer it allows to publish new messages even if broker cannot accept more.
This PR introduces a new exception `AMQPConnectionBlockedException` which can be thrown in methods `basic_publish()` and `publish_batch()`.
Some minor style improvements.
> Blocked connection check

- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/Connection/ConnectionClosedTest.php
Previously library executed `select` between data frames and never for small ones(<8kb). Without this check it is really possible to write to closed connection, actually OS buffer rather than real wire.
With this PR we will check connection with `select` before each write.
In summary:
- perform `select` before each write
- check for `EOF` before write to stream connection, like it is for read operations
- additional check for missed heartbeat before write
- tests and style improvements
Fix for #787
Known issues:
- there is no way to check for `EOF` for socket connections and is almost impossible to detect closed socket connection without access to low level OS internals
> Perform socket/stream select before data write

- PhpAmqpLib/Wire/IO/AbstractIO.php
- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Connection/ConnectionClosedTest.php
Check last read & write activity before throwing missed broker heartbeat exception.
fix #793
> Fix unexpected missed heartbeat exception

- .gitattributes
Excludes files and dirs:
- .github/
- docker/
- docs/
- spec/
- .gitmodules
- CONTRIBUTING.md
- CREDITS
- docker-compose.yaml
> Exclude non-essential files from dist

- PhpAmqpLib/Connection/AMQPSSLConnection.php
Required if multiple AMQP servers are behind a TLS termintator/load-balancer.
> Enable TLS SNI by setting peer_name to $host in $ssl_options

- .travis.yml
- docker-compose.yaml
- tests/docker-compose.travis.yaml
- tests/phpinfo.php
- tests/wait_broker.php
This will let us enable user authentication and secure connection tests much more easier. We will use broker and proxy instances in docker containers while PHP stays locally installed. That's why we need to have special network config for travis environment and broker wait script.
> Use docker containers for broker and proxy in travis CI tests

- PhpAmqpLib/Connection/AMQPSSLConnection.php
Looks like SSL context must be created with all esential options otherwise PHP fails to connect with "unknown error".
#785 introduced backward incompatible changes. Fix #825
> revert #785 'Enable TLS SNI by default'

- PhpAmqpLib/Channel/AMQPChannel.php
- tests/Functional/Channel/ChannelConsumeTest.php
- tests/Unit/Channel/AMQPChannelTest.php
This will prevent from cases, when `AMQPChannel::basic_consume()` with empty `$consumer_tag` and `$nowait=true` can overwrite previous callback or callback won't be called on new message.
Also, improved doc block and tests.
Should be last for bugfix version 2.12.1
> validate basic_consume() arguments and avoid invalid callbacks

- .github/workflows/phpunit.yml
- tests/wait_broker.php
Use github actions to run PHPUnit tests on each push & PR. Pretty much like travis-ci.
Only linux host for a while. Will add more platforms later for better coverage.
> perform CI tests using github actions

- PhpAmqpLib/Wire/AMQPAbstractCollection.php
- tests/Unit/Wire/AMQPCollectionTest.php
Implement \ArrayAccess in AMQPAbstractCollection, so we can use AMQPTable as array, for example:
```php
$a = new Wire\AMQPTable();
$a['test'] = 'value';
unset($a['test']);
```
> Implement \ArrayAccess in AMQPAbstractCollection

- PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
- tests/Functional/Connection/Heartbeat/PCNTLHeartbeatSenderTest.php
This is a fix for PCNTL heartbeat signal registration/chaining issue described in https://github.com/php-amqplib/php-amqplib/issues/865
> fix PCNTL heartbeat signal registration

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Helper/Protocol/Protocol080.php
- PhpAmqpLib/Helper/Protocol/Protocol091.php
- PhpAmqpLib/Wire/Constants080.php
- spec/parser.php
As reported in #873, AMQPTable is allowed variable type in several methods.
> fix annotation when AMQPTable is allowed variable type

- .github/workflows/phpunit.yml
- PhpAmqpLib/Helper/BigInteger.php
- PhpAmqpLib/Wire/AMQPDecimal.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/AMQPWriter.php
- PhpAmqpLib/Wire/AbstractClient.php
- composer.json
By using class aliases, we can make this library compatible with any of two latest major versions of phpseclib/phpseclib. So we neither block or enforce any upgrades, users can choose which version works best for them.
Tested on 32-bit windows and ARM platforms.
fixes #867
> Add support for next major version of phpseclib/phpseclib

- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Unit/Wire/IO/SocketIOTest.php
- tests/Unit/Wire/IO/StreamIOTest.php
Since PHP8.0 stream_select() throws exception instead of warning if something is wrong with socket. This was noticed first in PR #858 
Now we will throw relevant exception in such cases.
More context: https://github.com/reactphp/event-loop/issues/220#issuecomment-763389310
fix #883
> fix ValueError on closed or broken socket

- PhpAmqpLib/Helper/BigInteger.php
Issue #885
Replace phpseclib class alias with defined classes, otherwise authoritative class maps does not work as expected.
Created from 2.x branch, without latest master commits. Should be merged back to 2.x branch and released as bugfix version 2.12.3
I will merge into master branch afterwards.
> Fix phpseclib3 compatibility issue

- composer.json
Future versions of PHP (8.1, 9, ...) might break the code.
We need to be more specific on the list of supported php versions and
add the new versions when they will be released and tested.
> Change php required version in composer.json

- composer.json
Can't install using php7.4.
See here: https://jubianchi.github.io/semver-check/#/^7.0|~8.0.0/7.4
Fix: https://jubianchi.github.io/semver-check/#/^7.0||~8.0.0/7.4
> Fixed composer php version constraint

- demo/basic_get.php
- demo/basic_qos.php
- doc/AMQPMessage.md
Removed using of internal property `AMQPMessage::delivery_info` from docs and examples.
> Improved examples and dosc

- PhpAmqpLib/Wire/AMQPAbstractCollection.php
- PhpAmqpLib/Wire/AMQPReader.php
- tests/Unit/Wire/AMQPCollectionTest.php
- tests/Unit/Wire/AMQPReaderTest.php
- tests/Unit/Wire/AMQPWriterTest.php
- tests/Unit/WireTest.php
- tests/php_compat_70.php
- tests/ssl.php
Historically this library had no support for floating point values(float, double) in data tables and arrays. Such PHP values where converted and encoded as strings.
This PR will add decoding support for floating point values. Encoding stays same as it would introduce breaking change. So full fix will appear in next major version 4.0.
Besides that, data type mapping was updated according to RabbitMQ and AMQP0.9 standard[1].
fix #924
[1] https://www.rabbitmq.com/amqp-0-9-1-errata.html
> Add support for floating point values in tables/array

- PhpAmqpLib/Wire/AMQPAbstractCollection.php
Well known framework symfony has some deep compatibility analysis when debug mode is enabled. That analysis basically says, that we must declare return types or add docblock for some methods.
fix #967
> add return type hints in AMQPAbstractCollection

- .github/workflows/changelog.yml
- .github_changelog_generator
- CHANGELOG.md
- History.md
I suggest using automated changelog generator. No more hassle with manual edits!
It will be triggered after each github release(tagging via git is not enough). Old changelog is moved to History.md, we will use it as static part since versions 2.8.0.
More info and examples: https://github.com/github-changelog-generator/github-changelog-generator
> use github changelog generator

- PhpAmqpLib/Connection/Heartbeat/AbstractSignalHeartbeatSender.php
- PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
- PhpAmqpLib/Connection/Heartbeat/SIGHeartbeatSender.php
- tests/Functional/Connection/Heartbeat/SIGHeartbeatSenderTest.php
The existing `PCNTLHeartbeatSender` implementation uses `SIGALARM`
while convenient, for that use case, it also clashes with other libraries
that also want to use that same signal.
In our case, Laravel uses `SIGALARM` to define a timeout for job execution
on queue workers. Also a valid use case for it. But having both libraries
define their own signal handler for the same signal and overwrite each other's
alarm timeout makes a big mess where nothing works.
This allows defining a `pcntl_async_signals` handler that works with
a different signal than `SIGALARM`. The specific signal can be chosen at
construction time and is set to `SIGUSR1` by default.
The code uses `pcntl_fork` to create a separate process that sends the
chosen signal at regular intervals.
> Custom PCNTL Heartbeat Sender

- PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
We are having issues when using `PCNTLHeartbeatSender` to send heartbeat with signals. When our program is currently executing an SQL query with SQL Server and the signal occurs, it crashes the connection to SQL. This behavior has been reported in a few issues on github :
https://github.com/microsoft/msphpsql/issues/885
https://github.com/php/php-src/pull/3717
https://github.com/microsoft/msphpsql/issues/1242
The problem is also that when registering a signal with `pcntl_signal`, the third parameter (`$restart_syscalls`) has a default value set to `true` BUT, while not documented on PHP website, if the signal is SIGALRM and the parameter is not specified (we would think it would be true), PHP forces it to be false. However, if $restart_syscalls is explicitly passed when calling …
> Add $restart_syscalls = true explicitly when calling pcntl_signal to avoid crashing SQL Server connections

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
The pr adds real exceptions to target method `AbstractConnection::channel`.
Developer will can understand transparently that method `channel` can throw `AMQPTimeoutException,AMQPConnectionClosedException ` and do `reconnect`
> Propagate real exceptions

- PhpAmqpLib/Connection/AMQPConnectionConfig.php
- PhpAmqpLib/Connection/AMQPConnectionFactory.php
- PhpAmqpLib/Connection/AMQPLazyConnection.php
- PhpAmqpLib/Connection/AMQPLazySSLConnection.php
- PhpAmqpLib/Connection/AMQPLazySocketConnection.php
- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Connection/AMQPStreamConnection.php
- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Functional/AbstractConnectionTest.php
The aim of this PR is to put all connection configuration options into one object and reuse it for all kind of connections. Having this, we can improve several things:
- get rid of long argument list in each connection class
- unify default values
- deprecate global constants - once defined, they cannot be changed
- useable in applications with dependency injection(DI)
For now, previous approach takes precendence. Class arguments and global constants over connection config. This wil be canged in next major version.
> unified configuration class and factory for all kinds of connection

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- demo/amqp_consumer.php
- demo/amqp_consumer_exclusive.php
- demo/amqp_consumer_fanout_1.php
- demo/amqp_consumer_fanout_2.php
- demo/amqp_consumer_pcntl_heartbeat.php
- demo/basic_nack.php
- demo/delayed_message.php
This is a simple and very convenient method for endless consume loop. It does all neccessary things like handling no-data exceptions and picking correct polling timeout according to read timeout and heartbeat.
This loop can be stopped by Unix signal or using method `stopConsume()`.
Fix #458
> Channel method for continuous message consumption

- PhpAmqpLib/Channel/AMQPChannel.php
- tests/Unit/Channel/AMQPChannelTest.php
- tests/Unit/Test/TestChannel.php
Hello,
in bulk publishing, the connection existence is not checked (PhpAmqpLib/Channel/AMQPChannel.php:1232 in publish_batch method) and therefore we can't catch proper exception, like for example AMQPChannelClosedException.
This sometimes happens when there is a delay between opening the connection and actual publishing and for example in the meantime connection was closed for any reason whatsoever.
Therefore, here is the suggestion to throw a proper exception already in the prepare_method_frame method, like it's done for send_method_frame method in the AbstractChannel class.
> Throw connection exceptions on batch publish

- .github/workflows/code-style.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .github/workflows/changelog.yml
- .github/workflows/code-style.yml
- .github/workflows/documentation.yml
- .github/workflows/phpunit.yml
- docker-compose.yaml
- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Connection/ConnectionClosedTest.php
This will enable all connection stability tests using toxiproxy. Previously some tests were skipped on github actions CI.
> Upgrade toxiproxy, enable all tests on CI

- PhpAmqpLib/Connection/AMQPConnectionConfig.php
- PhpAmqpLib/Connection/AMQPSocketConnection.php
- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/SocketIO.php
- tests/Functional/AbstractConnectionTest.php
- tests/Unit/Wire/IO/SocketIOTest.php
All data written to sockets goes to OS buffer at first, while the real network transfer happens only when buffer is full(?). Usually this approach is effective and improves transfer speeds a lot. But at the same time due that buffering PHP don't see if something goes wrong with the network. Some operating systems have 200-300kb buffer which can accommodate many data frames.
This PR allow set lower buffer size as compromise between speed and lost data amount on network issues.
By default we still use system defined buffer size, so no breaking changes introduced.
> Allow set socket send buffer size

- .github/workflows/phpunit.yml
Codecov action v1 is not supported and does not work anymore.
https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1
fix #1027
> Update codecov action to latest version

- PhpAmqpLib/Connection/AbstractConnection.php
Missed param PHPDoc in construct AbstractConnection for `?AMQPConnectionConfig $config = null`
> Missing PHPDoc param in AbstractConnection constructor

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/AMQPBufferReader.php
- PhpAmqpLib/Wire/AMQPByteStream.php
- PhpAmqpLib/Wire/AMQPIOReader.php
- PhpAmqpLib/Wire/AMQPReader.php
- PhpAmqpLib/Wire/AMQPWriter.php
- tests/Unit/Message/AMQPMessageTest.php
- tests/Unit/Test/TestConnection.php
- tests/Unit/Wire/AMQPReaderTest.php
- tests/Unit/WireTest.php
This will split AMQPReader into two separate classes, each for different type of input, either buffer or IO layer. Resolves long standing TODO and makes code cleaner, more understandable.
Also add missing type hints.
No functional or breaking changes. Only internal refactoring.
> Split buffer and IO readers into separate classes

- PhpAmqpLib/Connection/AMQPConnectionConfig.php
- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/AbstractConnectionTest.php
Fix #1013 
Follow up forgotten promise 🤔
https://github.com/php-amqplib/php-amqplib/pull/674#issuecomment-480256638
> Define default ssl context parameter

- PhpAmqpLib/Channel/AbstractChannel.php
- PhpAmqpLib/Channel/Frame.php
- PhpAmqpLib/Channel/Method.php
- PhpAmqpLib/Connection/AbstractConnection.php
- PhpAmqpLib/Wire/AMQPReader.php
This PR improves the speed and simplicity of binary message parser. Historically we use mb string functions for splitting and extracting parts of binary stream. But they can be replaced by unpack(), moreover, several calls can be combined into one.
In overall this PR has:
2 less in-memory read buffers
5 less mb_* calls
4 less unpack() calls
faster SplQueue instead of array for frame queue
less temporary arrays
constants instead of hardcoded strings for readability
no functional changes
When measuring with `make benchmark` it shows
~15% better performance using my macbook pro 2,3 GHz Quad-Core Intel Core i7, PHP 7.4
~17% using 32bit raspberry pi 3, PHP 7.3
> Optimize frame parsing logic

- .github/workflows/phpunit.yml
- tests/rabbitmq.conf
Uses a `rabbitmq.conf` file rather than env vars
> Update GHA to use latest RabbitMQ

- PhpAmqpLib/Connection/AMQPConnectionConfig.php
- PhpAmqpLib/Connection/AMQPSSLConnection.php
- PhpAmqpLib/Wire/IO/StreamIO.php
- phpunit.xml.dist
- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Connection/AMQPStreamConnectionTest.php
- tests/Functional/Connection/SSLConnectionTest.php
> Revert #1060

- PhpAmqpLib/Connection/Heartbeat/AbstractSignalHeartbeatSender.php
- PhpAmqpLib/Connection/Heartbeat/PCNTLHeartbeatSender.php
- PhpAmqpLib/Connection/Heartbeat/SIGHeartbeatSender.php
- tests/Functional/Connection/Heartbeat/PCNTLHeartbeatSenderTest.php
- tests/Functional/Connection/Heartbeat/SIGHeartbeatSenderTest.php
Make heartbeat sender work with lazy connections, more info in #1099 
fix #1099
> feat(heartbeat): add support for lazy connections

- .github/workflows/phpunit.yml
- PhpAmqpLib/Connection/AMQPConnectionConfig.php
- appveyor.yml
- composer.json
- docker/php/Dockerfile
According to packagist stats[1], PHP7.1 share is less than 1.5%. I think it is time to drop support for it and get rid of some workarounds. Probably we can go further in next minor versions as PHP8.3 is comming and we don't want to have a long list of supported versions.
Minimum required version now is 7.2
[1] https://stitcher.io/blog/php-version-stats-july-2023
> drop support for PHP7.1

- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Bug/Bug256Test.php
- tests/Functional/Channel/ChannelConsumeTest.php
- tests/Functional/Connection/AMQPStreamConnectionTest.php
- tests/Functional/Connection/ConnectionClosedTest.php
- tests/Functional/Connection/ConnectionCreationTest.php
- tests/Functional/Connection/ConnectionUnresponsiveTest.php
- tests/Functional/Connection/Heartbeat/PCNTLHeartbeatSenderTest.php
- tests/Functional/Connection/Heartbeat/SIGHeartbeatSenderTest.php
- tests/Functional/Connection/Heartbeat/SignalHeartbeatTest.php
- tests/Functional/Connection/SSLConnectionTest.php
- tests/Unit/Connection/AMQPConnectionConfigTest.php
Introduce new unit tests to improve the test coverage for the AMQPConnectionConfig class. 
The tests validate:
- Invalid port number
- Invalid login method
- Invalid SSL settings
- Invalid AMQP protocol
- Invalid stream context
And also some typo fixes.
> Add Additional Test Coverage for AMQPConnectionConfig Class

- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
The current code calls fwrite() even when select_write() returns 0, ie when the write is expected to fail with EAGAIN (Resource temporarily unavailable). This happens if the TCP transmit buffer is full.
In real life I have seen select() return 0 and fwrite() succeeds anyway - I guess some room became available between the two calls.
But at one point fwrite() *will* fail with EAGAIN - and then an AMQPIOException occurs.
With the proposed changes fwrite() will not result in EAGAIN. Instead the result is an AMQPTimeoutException if the fd is still blocking after $this->write_timeout.
(See https://github.com/php-amqplib/php-amqplib/discussions/1131 for a question about how the timeout should be calculated).
I don't know if this change should include any new tests.
I have used `rabbitmqctl …
> Only call fwrite() if select() said the fd is ready.

- PhpAmqpLib/Connection/AMQPStreamConnection.php
Resolves #1136.
This PR simply widens the type of the parameter, but potentially renaming it to `$ssl_options_or_config` is wise while this is yet to be removed?
> Widen `AMQPStreamConnection`'s `$ssl_protocol` parameter to accept `AMQPConnectionConfig`

- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Functional/AbstractConnectionTest.php
- tests/Functional/Connection/ConnectionResourceLeakTest.php
Move stream context initialization from constructor to method `connect()`. This will make creation of lazy connection faster.
Based on #1151 and has less references to stream context if none is provided via constructor.
Possibly solves #1152 , but no confirmation yet.
> Delay stream resource init

- PhpAmqpLib/Wire/IO/StreamIO.php
- tests/Unit/Connection/AMQPConnectionConfigTest.php
This fixes 2 issues introduced in version 3.6.0:
* all warnings from function `stream_socket_enable_crypto()` are ignored and it's not good, because they provide valueable info about wrong SSL options or peer validation issues. Any consequent call to that method makes no sense since handshake is failed and connection is not useable at all.
* no proper check for function return value -  according to docs, function returns 0 _if there isn't enough data and you should try again_, _false if negotiation has failed_, but that is not checked and loop continues without any delay until timeout is reached
> fix: throw exception on stream_socket_enable_crypto() warning

- PhpAmqpLib/Connection/AMQPStreamConnection.php
- tests/Unit/Connection/AMQPStreamConnectionTest.php
As for PHP 8.0+ when using named params, func_num_args always return number of all params, because php de-facto inserts default values for that variables. This always generates deprecation warning.
In this PR I've deleted check for arguments number and leave only check for not null or AMQPConnectionConfig instance. That's enough for triggering deprecation.
For not named arguments nothing changes
> Trigger ssl_protocol deprecation when it is really not null and not AMQPConnectionConfig instance

- PhpAmqpLib/Wire/IO/AbstractIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
As described in #1181 , only last warning message is exposed making debugging more difficult.
After this change each warning will be stored as exception with reference to previous. Last one won't have $previous.
All errors(in reverse order) can be extracted by iterating recursively over previous exceptions:
```php
$previous = $exception;
do {
$messages[] = $previous->getMessage();
$previous = $exception->getPrevious();
} wihle ($previous !== null);
```
> fix: create a new exception for each warning in IO layer with reference to previous

- .ci/ubuntu/enabled_plugins
- .ci/ubuntu/gha-log-check.sh
- .ci/ubuntu/gha-setup.sh
- .ci/ubuntu/rabbitmq.conf
- .github/workflows/phpunit.yml
- .gitignore
- CONTRIBUTING.md
- Makefile
- PhpAmqpLib/Wire/IO/StreamIO.php
- README.md
- docker-compose.yaml
- docker/php/Dockerfile
- test.env
* Start RabbitMQ using `docker run` so a restart is not necessary.
* Use latest `toxiproxy` version
@ramunasd I've copied some scripts from [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/main/.ci/ubuntu) to set up GitHub actions for tests. In another PR, I'll do the same for Windows tests, and remove the AppVeyor build.
> CI workflow updates

- PhpAmqpLib/Channel/AMQPChannel.php
Hi,
This is a minor update to make the doc block of `checkConnection()` more accurate.
> AMQPConnectionClosedException is never thrown from checkConnection()

- PhpAmqpLib/Wire/IO/SocketIO.php
- PhpAmqpLib/Wire/IO/StreamIO.php
This will fix workaround which was introduced in #1179. After latter PR, stream IO always reports exceptions with code `999`, which is not correct.
Also, -1 `mb_substr()` for data frames which are smaller than maximum buffer size, to improve write performance.
> Fix wrong stream IO error code, improve write speed

- PhpAmqpLib/Channel/AMQPChannel.php
- PhpAmqpLib/Connection/AbstractConnection.php
- tests/Functional/Connection/ConnectionClosedTest.php
- tests/Unit/Channel/AMQPChannelTest.php
- tests/Unit/Connection/AbstractConnectionTest.php
When a connection gets broken (Got AMQPConnectionClosedException) we need to mark all opened channels as closed OR it can lead to some bugs.
- 3.7.0
- 3.7.1
I added a new call to the `\PhpAmqpLib\Connection\AbstractConnection::do_close`, but I'm sure that it's the most proper way to fix this problem.
```php
$connection = new \PhpAmqpLib\Connection\AMQPStreamConnection(
$host,
$port,
$user,
$pass,
);
$firstChannel = $connection->channel();
$secondChannel = $connection->channel();
$firstChannel->queue_declare('test');
$firstChannel->basic_consume('test', '', false, true, false, false, function (\PhpAmqpLib\Message\AMQPMessage $message) {
$message->ack();
});
try {
$firstChannel->wait();
// Emulate closing: force close connection using management plugin
} catch …
```
> fix: Mark channels closed when connection is closed

- README.md
Code blocks are already formatted, and GitHub provides a copy button. The $ symbol caused inconvenience because users had to manually remove it after pasting the command into the terminal.
Also, please update the description link (www.rabbitmq.com/getstarted.html). Now it redirects to https://www.rabbitmq.com/tutorials
> Remove unnecessary $ from code blocks in README
