php-amqplib/php-amqplib

PhpAmqpLib/Helper/MiscHelper.php
Thank you very much for the fix on #236, really and thank you more the reactivity.
This small PR brings an alternative to single quote "convention" break and bring back the single quote. I also made minor language-wise changes.
=> Stick to single quote convention + minor changes

PhpAmqpLib/Channel/AMQPChannel.php, PhpAmqpLib/Channel/AbstractChannel.php, PhpAmqpLib/Wire/AMQPReader.php, PhpAmqpLib/Wire/AMQPWriter.php
This PR fixed randomly occurring error "'Server nack\'ed unknown delivery_tag 1.00000000" and problems.
This resolves issue: https://github.com/videlalvaro/php-amqplib/issues/180
=> Fix for unknown delivery tag

composer.json
see https://github.com/videlalvaro/php-amqplib/issues/283
=> psr-0 > psr-4

README.md
Updated the composer version in the README from 2.2.* to 2.5.*
=> Updated the version in README to the latest one

PhpAmqpLib/Channel/AbstractChannel.php
I've declared the class AbstractChannel as being an abstract class, as the naming suggests
=> Declared the class AbstractChannel as being an abstract class

doc/AMQPMessage.md
=> Typo within documentation

PhpAmqpLib/Message/AMQPMessage.php, README.md, demo/amqp_publisher.php, doc/AMQPMessage.md, tests/Functional/AbstractPublishConsumeTest.php, tests/Functional/FileTransferTest.php, tests/Functional/ReconnectConnectionTest.php
Adding some constants for the delivery modes would make code easier to write and read.
=> Add constants for delivery modes

CHANGELOG.md
Starting the process to create changelog. :-)
PR for #315
=> Start of a changelog

.gitattributes, .scrutinizer.yml, .travis.yml, CONTRIBUTING.md, README.md, bin/ci/before_build.sh, composer.json
@videlalvaro Let me know if I've taken this too far. :-)
I wanted to get this project to follow some more of the open source package conventions.  Much of this was based on the PHP League's skeleton project (https://github.com/thephpleague/skeleton).  In doing so I've added the following:
* Scrutinizer (You'll need to create a scrutinizer-ci.com account if you don't already have one)
* Added a CONTRIBUTING.md
* Updated the travis.yml file
* Updated the README.md file to include some new "badges"
Let me know if there is anything here you don't agree with...
=> Open Source project updates

PhpAmqpLib/Channel/AMQPChannel.php, PhpAmqpLib/Channel/AbstractChannel.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Helper/MiscHelper.php, PhpAmqpLib/Message/AMQPMessage.php, PhpAmqpLib/Wire/AMQPDecimal.php, PhpAmqpLib/Wire/AMQPReader.php, PhpAmqpLib/Wire/AMQPWriter.php, PhpAmqpLib/Wire/GenericContent.php, PhpAmqpLib/Wire/IO/StreamIO.php, README.md
According to #193, here's the PR that refacto some parts of the lib: condition simplifications, better variable naming, better exception message building, etc.
Feedback and contribution is very welcomed.
Thanks,
=> Minor complexity optimizations + code organization

composer.json
@nubeiro @videlalvaro Feel free to update the branch and add email, homepage, or whatever you'd like before merging this.
=> Update authors section of composer

CODE_OF_CONDUCT.md, README.md
Thoughts or concerns about adding this CoC to the project?  Please avoid the "drama"...  :-)
=> Add Contributor Code of Conduct

PhpAmqpLib/Connection/AMQPLazySocketConnection.php, tests/Functional/ReconnectConnectionTest.php
Speaking of #331 . I wanted to have a generic lazy connection class that wraps real connection. But current class structure so flawed so I ended up with this simple solution.
Closes #331
=> Lazy socket connection

demo/amqp_consumer.php, demo/amqp_consumer_exclusive.php, demo/amqp_consumer_fanout_1.php, demo/amqp_consumer_fanout_2.php, demo/amqp_consumer_non_blocking.php, demo/amqp_consumer_signals.php, demo/amqp_ha_consumer.php, demo/amqp_message_headers_recv.php, demo/amqp_message_headers_snd.php, demo/amqp_publisher.php, demo/amqp_publisher_exclusive.php, demo/amqp_publisher_fanout.php, demo/amqp_publisher_with_confirms.php, demo/amqp_publisher_with_confirms_mandatory.php, demo/basic_cancel.php, demo/basic_get.php, demo/basic_nack.php, demo/basic_qos.php, demo/basic_return.php, demo/batch_publish.php, demo/delayed_message.php, demo/e2e_bindings.php, demo/queue_arguments.php, demo/ssl_connection.php
...as well as some variable naming changes.
=> Update DEMO files closer to PSR-2 standards

.travis.yml, PhpAmqpLib/Channel/AbstractChannel.php, composer.json, tests/Functional/AbstractPublishConsumeTest.php, tests/Functional/ChannelTest.php
=> Fix issue with declaring an exchange with a closed connection

PhpAmqpLib/Channel/AMQPChannel.php
Support unbinding of exchanges with arguments, fixes #409.
=> Fix exchange_unbind arguments

PhpAmqpLib/Wire/IO/StreamIO.php
Reverts php-amqplib/php-amqplib#460 per user feedback.
=> Revert "Ensure integer values are actually integers for HHVM compatibility"

PhpAmqpLib/Connection/AMQPLazyConnection.php, PhpAmqpLib/Connection/AMQPLazySocketConnection.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Wire/AMQPReader.php, PhpAmqpLib/Wire/AMQPWriter.php
=> fix for issues #415 and #261 - using empty($this->...) instead of ! $this

.travis.yml, PhpAmqpLib/Connection/AMQPLazyConnection.php, PhpAmqpLib/Connection/AMQPLazySocketConnection.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Wire/AMQPAbstractCollection.php, PhpAmqpLib/Wire/AMQPReader.php, PhpAmqpLib/Wire/AMQPWriter.php, PhpAmqpLib/Wire/IO/StreamIO.php, README.md, tests/Unit/Wire/AMQPCollectionTest.php
Adds the necessary code to check if the script is being run under HHVM and set the timeout parameters accordingly before calling stream_select
=> Add work-around to fix 462

README.md
Document that the lib requires the bcmath and mbstring extensions.
=> Add extensions requirements to Readme.md

PhpAmqpLib/Channel/AbstractChannel.php, PhpAmqpLib/Wire/GenericContent.php, PhpAmqpLib/Wire/IO/SocketIO.php, tests/Unit/Helper/MiscHelperTest.php, tests/Unit/Message/AMQPMessageTest.php, tests/Unit/Wire/AMQPDecimalTest.php, tests/Unit/Wire/IO/SocketIOTest.php
Increased overall test coverage by writing some unit tests, even if they were too simple. Simplified, removed unnecessary comments, codes.
=> Increased overall test coverage.

CHANGELOG.md
This pull request should be the last merge for v2.7.0-rc1. 
It documents in CHANGELOG.md file notable changes since last release.
=> Update changelog for v2.7.0-rc1

CONTRIBUTING.md, README.md
Hey guys, 
Since 2.7 has been released it would make sense to update the readme as well 🙂
=> Readme update for version 2.7

README.md
https://github.com/php-amqplib/php-amqplib/pull/500 could be closed.
=> Add a link to amqp interop compatible transport.

tests/Unit/Helper/MiscHelperTest.php, tests/Unit/Helper/Protocol/Protocol091Test.php, tests/Unit/Wire/AMQPCollectionTest.php, tests/Unit/Wire/AMQPDecimalTest.php, tests/Unit/Wire/AMQPWriterTest.php, tests/Unit/Wire/IO/SocketIOTest.php
Some fixes from [`PHPStan`](https://github.com/phpstan/phpstan)
=> Fixes from PHPStan level 0

tests/Functional/AbstractPublishConsumeTest.php, tests/Functional/Bug256Test.php, tests/Functional/Bug40Test.php, tests/Functional/Bug49Test.php, tests/Functional/FileTransferTest.php, tests/Functional/ReconnectConnectionTest.php, tests/Functional/StreamIOTest.php, tests/Unit/Channel/AMQPChannelTest.php, tests/Unit/Helper/MiscHelperTest.php, tests/Unit/Helper/Protocol/Protocol091Test.php, tests/Unit/Message/AMQPMessageTest.php, tests/Unit/Wire/AMQPCollectionTest.php, tests/Unit/Wire/AMQPDecimalTest.php, tests/Unit/Wire/AMQPWriterTest.php, tests/Unit/Wire/IO/SocketIOTest.php, tests/Unit/Wire/IO/StreamIOTest.php, tests/Unit/WireTest.php
=> Merge PR #519

.gitmodules, Makefile, PhpAmqpLib/Channel/AbstractChannel.php, composer.json, demo/amqp_consumer_non_blocking.php
Fixes #513 
Includes #518 and #529
=> Generate API documentation

PhpAmqpLib/Connection/AbstractConnection.php
There is currently no handling for a missed heartbeat event from the server. This pull request uses the local heartbeat timer, `$this->heartbeat` and throws an `AMQPRuntimeException` if `$this->heartbeat * 2` seconds pass without receiving any frame from the server.
I still don't have a great mental picture of the timeout handling and blocking behavior in PhpAmqpLib. If the user specifies a timeout value to the `wait` method that is greater than `$this->heartbeat`, or does not specify a timeout at all thus causing the IO layer to wait indefinitely for traffic, we will still be at the mercy of the host OS to close the dead socket. Is this behavior correct? Or should we continue waiting until the user's requested timeout, but make the internal read timeout sooner and throw the exception if …
=> Throw exception when server heartbeat missed

PhpAmqpLib/Wire/IO/StreamIO.php
=> Fix possible indefinite waiting for data in StreamIO

PhpAmqpLib/Connection/AMQPLazyConnection.php, PhpAmqpLib/Connection/AMQPLazySocketConnection.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Wire/IO/AbstractIO.php, PhpAmqpLib/Wire/IO/SocketIO.php
Additional changes required by #520
=> Ensure access levels are consistent

PhpAmqpLib/Channel/AMQPChannel.php
Whenever there is an array argument, this should be the preferred
default value.
=> Use array as a default argument

PhpAmqpLib/Wire/GenericContent.php
Cleanup serialized_properties on property set
=> Cleanup serialized_properties on property set

PhpAmqpLib/Wire/AMQPReader.php, PhpAmqpLib/Wire/IO/StreamIO.php
=> Fix potential indefinite wait

PhpAmqpLib/Wire/IO/StreamIO.php
Fix for typo, see #637 for details
=> Fixed typo that may cause fatal error in runtime

PhpAmqpLib/Channel/AMQPChannel.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Wire/IO/SocketIO.php, PhpAmqpLib/Wire/IO/StreamIO.php, tests/Functional/Bug/Bug458Test.php, tests/Functional/Channel/ChannelWaitTest.php
=> Fix regression after #642

demo/amqp_consumer_signals.php
fix #489 
also #650 is required because of fix at https://github.com/php-amqplib/php-amqplib/pull/650/files#diff-5392acd70f1025abd651d60a8a8007c4R165
otherwise loop `while($this->channel->callbacks)` won't finish even if channel is closed.
=> Fix signals demo

PhpAmqpLib/Wire/IO/SocketIO.php, PhpAmqpLib/Wire/IO/StreamIO.php, tests/Unit/Wire/IO/SocketIOTest.php, tests/Unit/Wire/IO/StreamIOTest.php
Reverts some of #648
Fixes #666
=> Revert argument checking

PhpAmqpLib/Wire/IO/StreamIO.php
=> Fix undefined constant

PhpAmqpLib/Channel/AMQPChannel.php, PhpAmqpLib/Channel/AbstractChannel.php, PhpAmqpLib/Connection/AbstractConnection.php, benchmark/consumer.php, benchmark/file_consume.php, demo/amqp_consumer.php, demo/amqp_consumer_exclusive.php, demo/amqp_consumer_fanout_1.php, demo/amqp_consumer_fanout_2.php, demo/amqp_consumer_non_blocking.php, demo/amqp_consumer_signals.php, demo/amqp_ha_consumer.php, demo/amqp_message_headers_recv.php, demo/basic_nack.php, demo/basic_qos.php, demo/delayed_message.php
No functional chages, only docblocks and style improvemets.
=> Deprecate access to internal properties and methods

demo/amqp_consumer.php
=> fix unknown var

CONTRIBUTING.md, PhpAmqpLib/Channel/AMQPChannel.php, demo/connection_recovery_consume.php
Fixing phpdoc because I hate when my analyzer complains
=> Fix phpdoc

.travis.yml, composer.json, phpunit.xml.dist, tests/Functional/Channel/DirectExchangeTest.php, tests/Unit/Message/AMQPMessageTest.php
- Let the repository require `php-7.0` version at least because the PHP 7 has been released for whiles.
- Change into the `7.0.0` in `PHPUnit` attribute setting.
- Using the `expectException` since the `PHPUnit` version is `6.5+`.
=> Resolves issue#718

CHANGELOG.md, PhpAmqpLib/Connection/AMQPSSLConnection.php, PhpAmqpLib/Connection/AMQPSocketConnection.php, PhpAmqpLib/Connection/AMQPStreamConnection.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Wire/IO/SocketIO.php, PhpAmqpLib/Wire/IO/StreamIO.php, tests/Unit/Wire/IO/StreamIOTest.php
=> Revert changes from #648

.travis.yml, phpunit.xml.dist
Spin up docker container and activate connection tests using toxiproxy.
Also, remove deprecated phpunit config options and listener.
=> Run toxiproxy based connection tests on travis-ci

PhpAmqpLib/Connection/AbstractConnection.php
Can we release version 2.10.1 ?
=> Update version number to 2.10

PhpAmqpLib/Connection/AbstractConnection.php
=> Fix AMQPTimeoutException handling

README.md
Couldn't decide if this was a new section or just a related library. Let me know and I can make adjustments as necessary.
=> Mention AMQProxy as related library

PhpAmqpLib/Channel/AMQPChannel.php, PhpAmqpLib/Channel/AbstractChannel.php, PhpAmqpLib/Connection/AMQPSocketConnection.php, PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Exception/AMQPException.php, PhpAmqpLib/Exception/AMQPProtocolException.php, PhpAmqpLib/Helper/MiscHelper.php, PhpAmqpLib/Wire/AMQPAbstractCollection.php, PhpAmqpLib/Wire/AMQPReader.php, PhpAmqpLib/Wire/GenericContent.php, PhpAmqpLib/Wire/IO/AbstractIO.php, PhpAmqpLib/Wire/IO/SocketIO.php, PhpAmqpLib/Wire/IO/StreamIO.php
* add missing and fix conflicting doc block definitions
* simplified if statements
* remove deprecated and unused method
* improve scrutinizer rating
=> Code style and static analysis warnings

PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Package.php
This is just one place for package meta information.
I suggest this PR is last in 2.11 series. We are ready to release 2.11.1 bugfix version.
=> Add package meta class

PhpAmqpLib/Channel/AMQPChannel.php, tests/Unit/Channel/AMQPChannelTest.php
=> add type check for basic_consume() callback

PhpAmqpLib/Wire/AMQPReader.php
Discovered by @phpstan
https://github.com/php-amqplib/php-amqplib/blob/c04881d9936cc49a7acd1041f8a4926b40e3265e/PhpAmqpLib/Wire/IO/AbstractIO.php#L96-L99
=> AbstractIO::select() never returns false

.travis.yml
- indentation
- caching /vendor is unstable
- long Docker options
- remove unused COMPOSER_FLAGS
=> Tidy up CI configuration

PhpAmqpLib/Connection/AbstractConnection.php
fix #804 
windows build https://ci.appveyor.com/project/ramunasd/php-amqplib/builds/34414002
=> add missing timeout param for connection handshake response

PhpAmqpLib/Helper/DebugHelper.php
=> use simple output instead of STDOUT in debug helper

PhpAmqpLib/Channel/AMQPChannel.php, tests/Functional/Message/AMQPMessageTest.php
This is a bugfix for LogixException issue which was introduced with #799
=> fix LogicException while waiting for pending broker ack

.github/workflows/documentation.yml, Makefile
This will ensure that phpdocs on http://php-amqplib.github.io/php-amqplib/ is always up to date.
Based on github actions and release webhook.
=> Update documentation on published release

PhpAmqpLib/Channel/AMQPChannel.php
To fix static analyzers warnings https://github.com/php-amqplib/php-amqplib/issues/835
=> Change phpdoc $delivery_tag type to int

PhpAmqpLib/Exception/AMQPException.php, PhpAmqpLib/Exception/AMQPProtocolException.php
Fixes https://github.com/php-amqplib/php-amqplib/issues/844
=> Fixed AMQPProtocolException phpdoc arguments type annotations

PhpAmqpLib/Helper/Protocol/Protocol080.php
Resolves: https://github.com/php-amqplib/php-amqplib/issues/903
I just made changes to reflect how the other version of the Protocol looks like.
=> PHP 8 support

PhpAmqpLib/Wire/IO/AbstractIO.php, PhpAmqpLib/Wire/IO/SocketIO.php, PhpAmqpLib/Wire/IO/StreamIO.php
Slightly improved error handling in in low level TCP communication methods. Previous approach can leave wrong custom handler under some very speific circumstances.
=> Always restore original error handler after socket/stream actions

PhpAmqpLib/Channel/AbstractChannel.php
Otherwise closed PR https://github.com/php-amqplib/php-amqplib/pull/980
=> getChannelId can return null

.github/workflows/changelog.yml
https://github.com/github-changelog-generator/github-changelog-generator#github-token
=> Fix rate limiting

PhpAmqpLib/Connection/AbstractConnection.php, tests/Functional/Connection/ConnectionCreationTest.php
=> Fix heartbeat negotiation

PhpAmqpLib/Connection/AbstractConnection.php, PhpAmqpLib/Wire/IO/AbstractIO.php
This fix regresion in hearbeat negotiation after #1024
fix #1029
=> Allow disable heartbeats from client side

PhpAmqpLib/Connection/AMQPSocketConnection.php, PhpAmqpLib/Connection/AMQPStreamConnection.php
Added channel_rpc_timeout to try_create_connection since it was missing as an option and it's a valid option to pass to the constructor.
=> Added channel_rpc_timeout

PhpAmqpLib/Connection/Heartbeat/SIGHeartbeatSender.php
=> Fix hardcoded signal code in SIGHeartbeatSender

PhpAmqpLib/Connection/AMQPConnectionConfig.php, PhpAmqpLib/Connection/AMQPConnectionFactory.php, PhpAmqpLib/Connection/AbstractConnection.php, tests/Unit/Connection/AMQPConnectionConfigTest.php, tests/Unit/Connection/AbstractConnectionTest.php
=> Support for authentication method "external"

PhpAmqpLib/Connection/AMQPConnectionConfig.php, PhpAmqpLib/Connection/AMQPConnectionFactory.php, PhpAmqpLib/Connection/AMQPLazyConnection.php, PhpAmqpLib/Connection/AMQPLazySSLConnection.php, PhpAmqpLib/Connection/AMQPLazySocketConnection.php, PhpAmqpLib/Connection/AbstractConnection.php, tests/Unit/Test/TestConnection.php
deprecate *LazyConnection classes which are basically wrappers with different defaults
=> Add support for lazy connect to all classes

PhpAmqpLib/Connection/AMQPConnectionFactory.php, PhpAmqpLib/Connection/AMQPSSLConnection.php, PhpAmqpLib/Connection/AMQPSocketConnection.php, PhpAmqpLib/Connection/AMQPStreamConnection.php
- Bug Fix for #1076
- Updated deprecation notice, to point to more specific class
=> Bug fix, Deprecation notice update

PhpAmqpLib/Connection/AbstractConnection.php, tests/Functional/Connection/ConnectionCreationTest.php
This is fix for a case described in #1080 as Example no. 2
=> Fix server heartbeat overwrite client value

PhpAmqpLib/Connection/AMQPConnectionConfig.php, PhpAmqpLib/Connection/AMQPSSLConnection.php, PhpAmqpLib/Wire/IO/StreamIO.php, docker-compose.yaml, tests/Unit/Connection/AMQPConnectionConfigTest.php
Auto set network protocol to ssl when isSecure is true
Auto set setSslVerifyName to false when setSslVerify is false
=> Adjust config for isSecure and setSslVerify

PhpAmqpLib/Connection/AMQPConnectionConfig.php, PhpAmqpLib/Connection/AMQPConnectionFactory.php, PhpAmqpLib/Connection/AMQPSSLConnection.php, PhpAmqpLib/Connection/AMQPStreamConnection.php, PhpAmqpLib/Wire/IO/StreamIO.php, tests/Functional/AbstractConnectionTest.php, tests/Functional/Connection/SSLConnectionTest.php, tests/Unit/Connection/AMQPConnectionConfigTest.php
Resolves [#371](https://github.com/php-amqplib/php-amqplib/issues/371).
Solution inspired by https://github.com/rtm-ctrlz/keepalive#streams-ssl
=> TCP keepalive for TLS connections

.github/workflows/changelog.yml, .github/workflows/code-style.yml, .github/workflows/documentation.yml, .github/workflows/phpunit.yml
Update actions/checkout to v4
https://github.com/actions/checkout/releases/tag/v4.0.0
=> Update checkout to v4

PhpAmqpLib/Channel/AMQPChannel.php, PhpAmqpLib/Helper/Protocol/Protocol091.php
Added more detail to the docblock for the `basic_qos` functions to help developers understand the parameters better.
=> Updated docblock

PhpAmqpLib/Wire/IO/AbstractIO.php, PhpAmqpLib/Wire/IO/SocketIO.php, PhpAmqpLib/Wire/IO/StreamIO.php
Docblock and type improvements in IO layer. No functional changes or changes in public API.
fixes #1155
=> fix static analysis warnings

.github/workflows/phpunit.yml
Try to figure out why certain tests are not running.
=> Add verbose test output
